[SOA-59] Social login with ally (#60)
* chore 🏗️ : add and configure ally

* feat 🎸 (be): add routes, controller and methods

* styles 💅 : add generic social buttons and divider components

* feat 🎸 (be): method completion

* fix ✅ : minor corrections

* chore 🏗️ : update README.md

* fix ✅ : config corrections based on env

* styles 💅 : improve loading/processing feedback on social buttons

* fix ✅ : hosteddomain env tweak

* chore 🏗️ (lint): review lint checking commands

* refactor ✨ : clean up dynamic get driver logic

* styles 💅 : add enabled flag to social login auth buttons

* refactor ✨ (types): utils TW types for prop colors

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,22 +1,7 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+echo '🏗️👷 Styling, formatting and typechecking your project before committing'
 
-echo '🏗️👷 Styling, testing and building your project before committing'
-
-yarn format ||
+yarn clean ||
 (
-    echo '😤🏀👋😤 Prettier Check Failed. Run yarn format, add changes and try to commit again.';
-    false;
-)
-
-yarn lint ||
-(
-    echo '😤🏀👋😤 ESLint Check Failed. Make the required changes listed above and try to commit again.'
-    false; 
-)
-
-yarn typecheck ||
-(
-    echo '😤🏀👋😤 TS Check Failed. Make the required changes listed above and try to commit again.'
+    echo '😤🏀👋😤 Pre-checks Failed. Make the required changes listed above and try to commit again.'
     false; 
 )
